# Generated by Django 4.2.1 on 2023-05-06 14:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_no',
            field=models.CharField(error_messages={'unique': 'This Employee No is already exists'}, max_length=4, unique=True, validators=[django.core.validators.MinLengthValidator(4, 'Employee No has to be 4 characters')]),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(error_messages={'unique': 'This Table Number already exists'}, unique=True)),
                ('number_of_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', default=None, on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tables',
            },
        ),
    ]
